deployment:
  replicaCount: 1
  image: sharnithadockerhub/dfthub01
resources:
  requests:
    cpu: "250m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"
service:
  port: 8080

